### PR TITLE
Rename SRIOV_USERSPACE to vfio.

### PR DESCRIPTION
**Pull request by edwarnicke**
Putting this out there as a draft for discussion on naming.  I look to folks who know this space better to tell me whether this is a good idea or a bad one :)

### CODE REVIEW

**Comment by przemeklal** [comment]
Already mentioned in the issue #15 - vfio is a really bad name.

**Comment by edwarnicke** [comment]
> Already mentioned in the issue #15 - vfio is a really bad name.

>Some of you proposed to include VFIO in the name. That's a huge no from me. The landscape changes all the time, new kernel versions introduce new mechanisms. Intel NICs can be used with any of vfio-pci, igb_uio or uio_pci_generic kernel module. It's not our problem.

Do those present as different kinds of device files?

**Comment by przemeklal** [comment]
Yes, each has its own mechanism - e.g. VFIO is represented as /dev/vfio/vfio and for UIO each device uses its own file like /dev/uio1, /dev/uio2. Underlying mechanisms are also slightly different (mostly low level stuff like memory addresses mapping/translation), although it's usually transparent for the userspace networking applications (and their users/operators).

**Comment by edwarnicke** [comment]
@przemeklal OK... so in my mind (again, you know this space better than I do), an application would need to ask for the *mechanism* it understood how to use (ie, vfio, uio, etc) ... so if my application only knows how to use vfio, I'd want to only have vfio as a *mechanism* in my MechanismsPreferences list, similarly for uio, etc.  If I can do both, I can put both in my Mechanism preferences list.

Does that make sense?  Am I missing anything?

**Comment by przemeklal** [comment]
@edwarnicke 
> so if my application only knows how to use vfio

I've never heard about such use case. For DPDK, which is de facto standard for userspace networking, it doesn't make any difference whether devices are using vfio, uio or bifurcated mode. Choosing the right driver depends more on the HW you have, OS and BIOS settings. For the application itself it shouldn't really matter. And even if there's some crazy scenario where it does, it can still be configured at the device plugin level. From my experience requesting userspace host device with some PCI address is all that the application will need. Plus eventually sometimes the IP address and configuration, but that's something that NSM is excellent at already.

**Comment by edwarnicke** [comment]
> @edwarnicke
> 
> > so if my application only knows how to use vfio
> 
> I've never heard about such use case. For DPDK, which is de facto standard for userspace networking, it doesn't make any difference whether devices are using vfio, uio or bifurcated mode. Choosing the right driver depends more on the HW you have, OS and BIOS settings. For the application itself it shouldn't really matter. And even if there's some crazy scenario where it does, it can still be configured at the device plugin level. From my experience requesting userspace host device with some PCI address is all that the application will need. Plus eventually sometimes the IP address and configuration, but that's something that NSM is excellent at already.

That's great if you are using DPDK, you just advertise you can support all three.  But not everything that uses NICs uses DPDK.  For example, VPP has a number of direct drivers for NICs, which do not use DPDK.  

Please also note, a Pod will have zero access to the HW or BIOS, and very unprivileged access to the kernel OS.  One of the issues I know DPDK is working through (may have already worked through) is dealing with the immutable infrastructureness of Cloud Native.  

The net-net point is: target the interfaces (ie, vfio, uio, bifurcated, kernel interface) being offered, not a particular choice of driver software (DPDK).

**Comment by przemeklal** [comment]
> That's great if you are using DPDK, you just advertise you can support all three. But not everything that uses NICs uses DPDK. For example, VPP has a number of direct drivers for NICs, which do not use DPDK.
> 
> Please also note, a Pod will have zero access to the HW or BIOS, and very unprivileged access to the kernel OS. One of the issues I know DPDK is working through (may have already worked through) is dealing with the immutable infrastructureness of Cloud Native.
> 
> The net-net point is: target the interfaces (ie, vfio, uio, bifurcated, kernel interface) being offered, not a particular choice of driver software (DPDK).

I still feel like there's a small mismatch here - first we mix taps, veths and kernel SRIOV interfaces as part of one mechanism and then introduce separate mechanisms for vfio and uio - which I feel are much more similar to one another and are going to be consumed in a basically the same way.

Anyway, if there are valid use cases for apps that may want to request VFIO and not accept UIO (the choice here may be often made due to security features now I think), then I'm fine with that approach. Maybe lets see how this works out and reconsider single common userspace mechanism if we'll start feeling that the overlap is too large (or all apps are always requesting both at the same time :wink:).

**Comment by nickolaev** [comment]
I agree with @przemeklal that in one case we mix, and the other we split. But yes, in the end let's move forward with whatever we have and see if we need to change later.

**Pull request merged**
