### PR TITLE
Delete unused helper functions

### PR DESCRIPTION
**Pull request by NikitaSkrynnik**
## Issue
https://github.com/networkservicemesh/api/issues/143

### CODE REVIEW

**Review by denis-tingaikin — APPROVED** [review]

**Comment by denis-tingaikin** [comment]
@arp-est, @bszirtes Could you please double check if you are using something from these functions in your code base?

**Review by bszirtes — APPROVED** [review]
LGTM.

**Comment by robaganrab** [comment]
Hello,
Can you please check if [Nordix/Meridio](https://github.com/Nordix/Meridio/) is using any of these functions?
Thank you.

**Comment by bszirtes** [comment]
I reviewed the [Nordix/Meridio](https://github.com/Nordix/Meridio/) repository and did not find any instances where the functions proposed for deletion are being used.

**Review by bszirtes — APPROVED** [review]

**Review by denis-tingaikin — APPROVED** [review]
@bszirtes , @robaganrab Many thanks for checking that. We can also test main branches on weekends and revert this if we face some problems.

Mergining..

**Pull request merged**
